version: "3.8"
services:
  backend:
    build:
      context: ./api
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
