version: "3.8"
services:
  backend:
    build:
      context: ./api
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: crossover.proxy.rlwy.net
      DB_PORT: 35641 
      DB_DATABASE: railway
      DB_USERNAME: root
      DB_PASSWORD: tQVoZIIkPBsBDIVmMHmUeCKFdCfJflKw

  frontend:
    build:
      context: ./
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - backend

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: tQVoZIIkPBsBDIVmMHmUeCKFdCfJflKw
      MYSQL_DATABASE: railway
    ports:
      - 35641 ":35641 "
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
